"""
Unit tests for NovaCool sim components.

Running with: python -m pytest tests/ -v
"""

import numpy as np
import pytest
from simulator.thermal import ThermalModel, ThermalConfig
from simulator.power import PowerModel, PowerConfig
from simulator.facility import NovaCoolFacility, load_workload
from env.datacenter_env import DataCenterEnv


# ThermalModel tests
class TestThermalModel:

    def setup_method(self):
        self.model = ThermalModel()
        self.supply = np.full(4, 7.0)
        self.fans   = np.ones(4)

    def test_zero_power_outlet_equals_inlet(self):
        """With no IT load, outlet equals inlet ideally (+ recirculation)."""
        rack_power = np.zeros(self.model.cfg.n_racks)
        result = self.model.step(rack_power, self.supply, self.fans)
        expected_inlet = 7.0 + self.model.cfg.recirculation_factor
        np.testing.assert_allclose(
            result["outlet_temp_c"], expected_inlet, atol=0.01
        )

    def test_outlet_always_greater_than_inlet(self):
        """Outlet must always be >= inlet (since heat flows from server to air)."""
        rack_power = np.random.uniform(5, 45, self.model.cfg.n_racks)
        result = self.model.step(rack_power, self.supply, self.fans)
        assert np.all(result["outlet_temp_c"] >= result["inlet_temp_c"])

    def test_higher_power_higher_outlet(self):
        """Doubling power should raise outlet temp."""
        low_power  = np.full(self.model.cfg.n_racks, 10.0)
        high_power = np.full(self.model.cfg.n_racks, 20.0)
        r_low  = self.model.step(low_power,  self.supply, self.fans)
        r_high = self.model.step(high_power, self.supply, self.fans)
        assert np.all(r_high["outlet_temp_c"] > r_low["outlet_temp_c"])

    def test_lower_supply_temp_lower_outlet(self):
        """Colder supply air should reduce outlet temp."""
        rack_power = np.full(self.model.cfg.n_racks, 30.0)
        r_warm = self.model.step(rack_power, np.full(4, 15.0), self.fans)
        r_cold = self.model.step(rack_power, np.full(4,  7.0), self.fans)
        assert np.all(r_cold["outlet_temp_c"] < r_warm["outlet_temp_c"])

    def test_output_shapes(self):
        """All output arrays must have the correct shapes."""
        n = self.model.cfg.n_racks
        c = self.model.cfg.n_crahs
        result = self.model.step(np.full(n, 20.0), self.supply, self.fans)
        assert result["inlet_temp_c"].shape      == (n,)
        assert result["outlet_temp_c"].shape     == (n,)
        assert result["hot_aisle_temp_c"].shape  == (c,)
        assert result["crah_cooling_kw"].shape   == (c,)

    def test_energy_conservation(self):
        """
        Heat removed by CRAHs must exceed heat generated by racks.

        Q_removed > Q_generated because the recirculation factor adds heat to the inlet air... CRAHs must remove both IT heat AND the recirculation penalty. This is physically correct.

        Q_removed = Q_it + Q_recirculation
        Q_recirculation = n_racks * mdot * cp * recirculation_factor
                        = 200 * 1.5 * 1006 * 1.5 / 1000 = 452ish kW
        """
        rack_power_kw = np.full(self.model.cfg.n_racks, 25.0)
        result = self.model.step(rack_power_kw, self.supply, self.fans)

        Q_gen_kw     = rack_power_kw.sum()
        Q_removed_kw = result["crah_cooling_kw"].sum()

        # CRAHs must remove at least the IT heat
        assert Q_removed_kw >= Q_gen_kw, (
            "CRAHs must remove at least as much heat as racks generate"
        )

        # Expected recirculation overhead
        cfg = self.model.cfg
        Q_recirc_kw = (
            cfg.n_racks * cfg.mdot_air_per_rack
            * cfg.cp_air * cfg.recirculation_factor
            / 1000.0
        )
        expected_total = Q_gen_kw + Q_recirc_kw

        # Q_removed should match IT + recirculation within 2%
        assert abs(Q_removed_kw - expected_total) / expected_total < 0.02, (
            f"Q_removed={Q_removed_kw:.1f} kW, expected ~{expected_total:.1f} kW"
        )

#PowerModel tests
class TestPowerModel:

    def setup_method(self):
        self.model = PowerModel()

    def test_ups_efficiency_peak(self):
        """UPS efficiency should peak at ~62.5% load."""
        eta_peak = self.model.ups_efficiency(6250.0)  #62.5% of 10MW
        eta_low  = self.model.ups_efficiency(1000.0)
        eta_high = self.model.ups_efficiency(9500.0)
        assert eta_peak > eta_low
        assert eta_peak > eta_high

    def test_pue_above_one(self):
        """PUE must always be >= 1.0 (overhead can't be -ve)."""
        result = self.model.step(
            it_load_kw=5000.0,
            crah_cooling_kw=np.full(4, 1250.0),
            crah_fan_fracs=np.ones(4),
        )
        assert result["pue"] >= 1.0

    def test_higher_fan_speed_higher_fan_power(self):
        """Cube law==> halving fan speed should reduce fan power by 8x."""
        r_full = self.model.step(5000.0, np.full(4, 1250.0), np.ones(4))
        r_half = self.model.step(5000.0, np.full(4, 1250.0), np.full(4, 0.5))
        ratio = r_full["fan_power_kw"] / r_half["fan_power_kw"]
        assert abs(ratio - 8.0) < 0.1  #cube law: (1.0/0.5)^3 = 8


# DataCenterEnv tests..
class TestDataCenterEnv:

    def setup_method(self):
        workload = load_workload("data/workload_trace.csv")
        facility = NovaCoolFacility(workload)
        self.env = DataCenterEnv(facility)

    def test_reset_returns_correct_shape(self):
        obs = self.env.reset()
        assert obs.shape == (self.env.OBS_DIM,)

    def test_step_returns_correct_types(self):
        self.env.reset()
        action = np.zeros(self.env.ACT_DIM)
        obs, reward, done, info = self.env.step(action)
        assert obs.shape == (self.env.OBS_DIM,)
        assert isinstance(reward, float)
        assert isinstance(done, bool)
        assert isinstance(info, dict)

    def test_episode_ends_at_1440(self):
        """Episode must terminate exactly at t=1440."""
        self.env.reset()
        action = np.zeros(self.env.ACT_DIM)
        done = False
        steps = 0
        while not done:
            _, _, done, _ = self.env.step(action)
            steps += 1
        assert steps == 1440

    def test_obs_normalised(self):
        """All observation values should be in approximately [0, 1]."""
        self.env.reset()
        action = np.zeros(self.env.ACT_DIM)
        for _ in range(10):
            obs, _, done, _ = self.env.step(action)
            assert np.all(obs >= -0.1), f"Obs below 0: {obs}"
            assert np.all(obs <=  1.5), f"Obs above 1: {obs}"
            if done:
                break

    def test_violation_gives_negative_reward(self):
        """
        Forcing very high supply temp should cause violations and -ve reward.
        """
        self.env.reset()
        # Push supply temp up by maximum delta every step
        n = self.env.n_crahs
        action = np.array([2.0]*n + [0.0]*n)
        total_reward = 0.0
        for _ in range(100):
            _, reward, done, info = self.env.step(action)
            total_reward += reward
            if done:
                break
        # After 100 steps of warming, should have accumulated violations...
        # this tests that the reward signal is working or not
        assert "n_violations" in info